### PR TITLE
fix: Fix not being able to issue new verification codes for emails with pending registration

### LINKED ISSUE #4522: Not able to request a new verification code for email registration
### Describe the bug

This issue [was first reported on Discord](https://discord.com/channels/1155780586871468093/1451995630665994422) as the impossibility of starting a new registration if a user did not verified the previous request. However, it highlighted another underlying problem which is the impossibility of requesting a new verification code until the current one has expired.

### To reproduce

With the Email IDP configured, request the creation of an account. Without verifying, request again with the same email. An exception will be thrown on the server and a dummy ID will be returned to the client.

```console
2025-12-20 17:48:12.741611Z  806866049 LOG            DEBUG                    message=Failed to start account registration for example@example.com, reason: email account request already exists
2025-12-20 17:48:12.742416Z  806866049 METHOD         emailIdp.startRegistration user=null, queries=2, duration=36µs
```

### Expected behavior

The previous request should be replaced by the new one.

### Library version

3.0.0 onwards.

### Platform information

N/A

### Additional context

N/A

### How experienced are you with this library?

Expert - Experienced and comfortable with using this library in complex projects

### Are you interested in working on a PR for this?

- [x] I want to work on this

### PR DESCRIPTION
**Pull request by marcelomendoncasoares**
Fixes #4522.

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

None.

### CODE REVIEW

File: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/providers/email/business/email_idp_server_exceptions.dart [hunk 1]
```diff
@@ -56,6 +56,10 @@ final class EmailAccountAlreadyRegisteredException
 final class EmailAccountRequestInvalidEmailException
     extends EmailAccountRequestServerException {}
 
+// NOTE: This exception is no longer being used after fixing the bug where
```
Comment (exaby73) [inline modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/providers/email/business/email_idp_server_exceptions.dart:59]: Could we add a `TODO` comment here and possibly log an issue for it?

Suggestion to create an umbrella issue to track deprecated symbols so that we can easily remove them in the next major version

File: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/test/email/email_idp/email_idp_start_password_reset_test.dart [hunk 2]
```diff
@@ -204,6 +204,82 @@ void main() {
     },
   );
 
+  withServerpod(
```
Comment (exaby73) [inline modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/test/email/email_idp/email_idp_start_password_reset_test.dart:207]: Can we add a test case to check if the old (now deleted) `requestId` is used to verify, it throws an error

File: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/test/email/email_idp/email_idp_start_registration_test.dart [hunk 3]
```diff
@@ -152,4 +152,67 @@ void main() {
       });
     },
   );
+
+  withServerpod(
```
Comment (exaby73) [inline modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/test/email/email_idp/email_idp_start_registration_test.dart:156]: Same test case for this one too

File: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/test/email/email_idp/email_idp_start_password_reset_test.dart (hunk 2 above)
Comment (marcelomendoncasoares) [reply modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/test/email/email_idp/email_idp_start_password_reset_test.dart:207]: I don't think this should be the scope of this test, since here we are only interested that the behavior of the `startPassword` method works as expected. Given the request is correctly created, we validate that completing works as expected in the `email_idp_finish_password_reset_test.dart` file.

File: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/test/email/email_idp/email_idp_start_registration_test.dart (hunk 3 above)
Comment (marcelomendoncasoares) [reply modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/test/email/email_idp/email_idp_start_registration_test.dart:156]: Same as above.

File: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/providers/email/business/email_idp_server_exceptions.dart (hunk 1 above)
Comment (marcelomendoncasoares) [reply modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/providers/email/business/email_idp_server_exceptions.dart:59]: I added a TODO comment at first, but then changed it to a NOTE since it is possible that we find a later usage for this exception.

I have intentionally avoided creating an issue to avoid bloating our backlog, but, since you are also suggesting it, we can have an issue marked as breaking for evaluating in the next major release. I would just have it separate per symbol instead of as an umbrella.

Comment (marcelomendoncasoares) [reply modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/providers/email/business/email_idp_server_exceptions.dart:59]: @coderabbitai Please create an issue for the NOTE on the code so we can track it before the next release.
