### PR TITLE
fix: Report exceptions during database start and healthcheck operations

### LINKED ISSUE #3294: Failed to connect to the database is not logged in `diagnosticEventHandlers`
### Describe the bug

serverpod 2.4.0 added an experimental feature

`diagnosticEventHandlers`

@christerswahn  implemented it here: https://github.com/serverpod/serverpod/pull/3187

But when starting the server & the databse is not available this is not logged. Because this fails to continue & start the server I would assume this is 

original issues to implement error handling in serverpod:
https://github.com/serverpod/serverpod/issues/1352
https://github.com/serverpod/serverpod/issues/3078

### To reproduce

Use this configuration

```
  var serverpod = Serverpod(
    ...
    experimentalFeatures: ExperimentalFeatures(
      diagnosticEventHandlers: [
        AsEventHandler((event, {required space, required context}) {
          print('$event  Origin is $space\n  Context is ${context.toJson()}');
        }),
      ],
    ),
  );
```

- turn off docker
- and see if your event handler is called when starting the server

### Expected behavior

The evenhandler should be called with the exception that the database could not be reached & connected to

### Library version

2.4.0

### Platform information

docker / macos

### Additional context

_No response_

### How experienced are you with this library?

Expert - Experienced and comfortable with using this library in complex projects

### Are you interested in working on a PR for this?

- [ ] I want to work on this

### PR DESCRIPTION
**Pull request by christerswahn**
Report exception events during database startup and health-check operations via the diagnostics handler. These areas were not covered before as reported in issue #3294.

Closes #3294 

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

n/a

### CODE REVIEW

**Review by SandPod — COMMENTED** [review]
Would it be possible to add some test that validate these continue to work as expected over time?

Starting the server without a database seems to cover a couple of these at least.

File: tests/serverpod_test_server/test_integration/diagnostics/diagnostic_events_test.dart [hunk 1]
```diff
@@ -281,4 +281,83 @@ void main() {
       expect(record.context, isA<WebCallOpContext>());
     });
   });
+
+  group(
+      'Given a serverpod server with a missing database and a diagnostic event handler, '
```
Comment (SandPod) [inline tests/serverpod_test_server/test_integration/diagnostics/diagnostic_events_test.dart:286]: Suggestion(NIT): Flip it around to clarify what is missing. (It seems like both are missing with the current description).

```suggestion
      'Given a Serverpod server with a diagnostic event handler and no database connection, '
```

**Review by SandPod — APPROVED** [review]
LGTM! 👍
