### PR TITLE
fix: Improves GitHub IDP and OAuth2 implementations

### LINKED ISSUE #3924: Sign in with Github
Add support for signing in with Github.

### PR DESCRIPTION
**Pull request by vfiruz97**
This PR addresses issues found in #4546 by simplifying the GitHub IDP configuration and improving OAuth2 token handling:

**Changes:**

Removed `GitHubOAuthCredentials` class - Simplified configuration by accepting `clientId` and `clientSecret` directly in `GitHubIdpConfig` instead of wrapping them in a separate credentials class.

Added `OAuth2PkceTokenResponse` class - OAuth2 token endpoint responses. Renamed for clarity - `parseAccessToken` → `parseTokenResponse` to better reflect that it parses the complete token response, not just the access token string.

Fixes #3924

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

### For `GitHubIdpConfig`:

```dart
// Before
GitHubIdpConfig(
  oauthCredentials: GitHubOAuthCredentials.fromJson({
    'clientId': clientId,
    'clientSecret': clientSecret,
  }),
)

// After
GitHubIdpConfig(
  clientId: clientId,
  clientSecret: clientSecret,
)
```

### For custom OAuth2 provider implementations:

``` dart
// Before
final ParseAccessToken parseAccessToken;

// After
final ParseTokenResponse parseTokenResponse;
```

### CODE REVIEW

**Comment by vfiruz97** [comment]
Hi @marcelomendoncasoares, take a look please.

File: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/common/oauth2_pkce/oauth2_pkce_token_response.dart [hunk 1]
```diff
@@ -0,0 +1,22 @@
+/// OAuth2 token response containing access token and optional metadata.
+class OAuth2PkceTokenResponse {
+  /// The access token issued by the authorization server.
+  final String accessToken;
+
+  /// The refresh token used to obtain new access tokens.
+  final String? refreshToken;
+
+  /// The lifetime in seconds of the access token.
+  final int? expiresIn;
```
Comment (marcelomendoncasoares) [inline modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/common/oauth2_pkce/oauth2_pkce_token_response.dart:10]: Question: Should we expose it as a `Duration` instead? Integer parameters for durations are always prone to interpretation error if we can avoid them.

Comment (vfiruz97) [reply modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/common/oauth2_pkce/oauth2_pkce_token_response.dart:10]: My recommendation is to keep it as `int`. The `expiresIn` field matches the raw OAuth2 specification [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749), where `expires_in` is always an integer representing seconds. If we were building a higher-level domain model that processes this data for application use, that would be the appropriate place to convert to Duration, but `OAuth2PkceTokenResponse` is intentionally a low-level response parser.
I'm good to convert it to Duration if you think that provides better DX

Comment (marcelomendoncasoares) [reply modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/lib/src/common/oauth2_pkce/oauth2_pkce_token_response.dart:10]: If having as `int` is more compliant with the RFC, I'm ok with keeping it that way.
