### PR TITLE
fix: Ensure dart sdk path is found correctly from compiled code as well

### LINKED ISSUE #4481: serverpod don't work with dart install.
### Describe the bug

`serverpod create` don't work if installed with `dart install serverpod_cli`.

### To reproduce

```sh
dart install serverpod_cli
serverpod create
```

### Expected behavior

Should work

### Library version

any

### Platform information

Dart 3.10 or later (for `dart install`)

### Additional context

_No response_

### How experienced are you with this library?

None

### Are you interested in working on a PR for this?

- [ ] I want to work on this

### PR DESCRIPTION
**Pull request by nielsenko**
## Description

Fix Dart SDK discovery for AOT-compiled serverpod CLI.

- `AnalysisContextCollection` cannot auto-detect SDK when running as compiled executable
- Add `_findDartSdk()` to explicitly locate SDK path
- Try `Platform.resolvedExecutable` first (works when running via `dart run`)
- Fall back to `DART_SDK` and `FLUTTER_ROOT` env vars
- Final fallback: locate `dart` via PATH and resolve symlinks
- Handles both pure Dart (`sdk/bin/dart`) and Flutter (`flutter/bin/cache/dart-sdk`) layouts

Fixes #4481

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else.
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

## Breaking changes

None.

## Summary by CodeRabbit

* **Improvements**
  * Enhanced Dart SDK detection in CLI analysis tools, now automatically resolving SDK paths from multiple sources across all supported platforms. The analyzer intelligently searches for SDK in environment variables, resolved executables, Flutter installations, and system PATH, improving cross-platform compatibility and tool initialization reliability.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by nielsenko** [comment]
Tests will follow in #4475

**Comment by nielsenko** [comment]
@coderabbitai review

File: tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart [hunk 1]
```diff
@@ -332,3 +333,48 @@ class EndpointsAnalyzer {
...
+    Platform.isWindows ? 'where' : 'which',
+    ['dart'],
+  );
+
+  if (result.exitCode != 0) return null;
+
+  final dartBin = (result.stdout as String).trim().split('\n').first;
+  final resolved = File(dartBin).resolveSymbolicLinksSync();
+
+  return _sdkPathFromDartExe(resolved);
```
[the remark this answers is not in the document]
Comment (nielsenko) [reply tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart:366]: It is okay to crash, if we cannot find the dart sdk. We cannot possible complete the generate without it.

**Comment by nielsenko** [comment]
Remember ..
> Tests will follow in #4475

File: tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart [hunk 2]
```diff
@@ -332,3 +333,48 @@ class EndpointsAnalyzer {
...
   }
 }
+
+String? _findDartSdk() {
+  // If running as a script, resolvedExecutable points to dart binary
+  var dartSdk = _sdkPathFromDartExe(Platform.resolvedExecutable);
+  if (dartSdk != null) return dartSdk;
+
+  // AOT compiled — check explicit env vars
+  dartSdk = Platform.environment['DART_SDK'];
```
Comment (SandPod) [inline tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart:346]: Question: Any risk this might mess up working with tools like fvm or puro?

File: tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart [hunk 3]
```diff
@@ -332,3 +333,48 @@ class EndpointsAnalyzer {
     return failingErrors;
   }
 }
+
+String? _findDartSdk() {
```
Comment (SandPod) [inline tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart:340]: Suggestion: Add documentation that mentions the Dart issue that should allow us to remove this code.

File: tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart (hunk 2 above)
Comment (nielsenko) [reply tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart:346]: I'm using puro myself, and it works fine with that.

For regular `dart run` invocation, this should do what `analyze` does internally today.

Compiled code will just fail to locate the sdk today, so this an improvement on that.

Writing tests for all kinds of setup feels futile.

File: tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart (hunk 3 above)
Comment (nielsenko) [reply tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart:340]: Added in [15e8e51](https://github.com/serverpod/serverpod/pull/4480/commits/15e8e5179bffb0f2dd2bdbd070743b9114d4df47)
