### PR TITLE
fix: Support DB exceptions outside transactions and parallel DB calls.

### LINKED ISSUE #2895: Detect database exceptions and rollback if they happen
**Describe the bug**
The following code is currently not supported in the test tools. The first create can throw a database exception which then invalidates the entire current transaction that the test is running in:
```dart
try {
  return await Resource.create();
} catch (e) {
  if (e is DatabaseException && e.isDuplicateKey()) {
    return await Resource.readFirst()
  }

  rethrow;
}
```
**Suggested solution**
- Wrap each database call inside the database proxy in a save point
- Rollback if a database exception happened
- Re-throw the database exception

It's impossible for the test tools to support this inside a transaction, which is already documented. But supporting it outside a transaction like the example above should be possible (as suggested).

### PR DESCRIPTION
**Pull request by hampuslavin**
## Description
Closes #2895 .

This PR fixes another issue related to emulated nested transaction in the test tools. When an error is raised inside a transaction, the transaction is no longer valid. Therefore the test tools needs to rollback before the error happened but still re-throw it out to the code under test.

Additionally, this PR introduces a synchronized lock to enable code like this:
```dart
test(
    'when creating multiple SimpleData in parallel '
    'then should have inserted all', () async {
  await Future.wait([
    SimpleData.db.insertRow(
      session,
      SimpleData(num: 1),
    ),
    SimpleData.db.insertRow(
      session,
      SimpleData(num: 2),
    ),
    SimpleData.db.insertRow(
      session,
      SimpleData(num: 3),
    ),
  ]);

  var simpleDatas = await SimpleData.db.find(session);

  expect(simpleDatas, hasLength(3));
  expect(simpleDatas.map((s) => s.num), containsAll([1, 2, 3]));
});
```

For rollbacks to work, there can never be more than a single operation that can fail going on at a single time. Therefore the test database proxy only allows a single database operation at a time. 

As soon as the user enters a concurrent mode which is not supported by this approach, an exception is thrown. These cases are:
- Concurrent transaction calls (already threw exception before this change)
- Non-transaction call concurrently happening during an ongoing transaction

## Changes
- Add synchronized lock to database operations in the database test proxy
- Add additional checks for invalid concurrent states that the test tools can't handle
- Unrelated fix to the issue, but this PR also releases save points when they are not needed anymore

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

### CODE REVIEW

**Review by Isakdl — APPROVED** [review]
LGTM 🚀, Nice job! Clear tests and easy to follow the logic!

File: tests/serverpod_test_server/test_integration/test_tools/database_operations_test.dart [hunk 1]
```diff
@@ -416,4 +416,99 @@ void main() {
...
+            simpleData =
+                await SimpleData.db.insertRow(session, SimpleData(num: 123));
+          }
+
+          expect(simpleData, isNotNull);
+          expect(simpleData?.num, 123);
+        });
+      });
+
+      test(
```
Comment (SandPod) [inline tests/serverpod_test_server/test_integration/test_tools/database_operations_test.dart:466]: Question: Are we guaranteed that the first transaction will always happen first? Since they are happening in "parallel" we shouldn't know or care which of the inserts happen first right?

Comment (hampuslavin) [reply tests/serverpod_test_server/test_integration/test_tools/database_operations_test.dart:466]: You're right! The test description should be updated to reflect that.

Comment (hampuslavin) [reply tests/serverpod_test_server/test_integration/test_tools/database_operations_test.dart:466]: 4bbe168
