### PR TITLE
fix: Only download templates on `create` command

### LINKED ISSUE #3770: `serverpod` command should not download and create templates files unless needed
### Problem to Solve

The `serverpod` command always downloads the templates folder before it processes any options or subcommands. This takes up to 2 seconds (on a good internet connection) on every invocation. 

This is the case even when running diagnostic invocations such as `serverpod version` and `serverpod help` (and when running with incorrect args so serverpod fails with error message). But running `serverpod version` should be very fast and - it is run from scripts and CI pipelines and should not slow them down.

If there is currently no internet connection, this also causes the serverpod command to always generate an error message and exit with an error code:

```sh
$ serverpod version
Downloading templates for version 2.9.1
Failed to download templates.
```

This is incorrect as the exit code should reflect if the command succeeded or not. `serverpod version` and `serverpod help` should always succeed if the command is properly installed.

### Proposal

Only download templates if the command being run needs them.

If running offline, the command should succeed if templates were previously downloaded.

### Use Case

- Running `serverpod version` in scripts should be fast and reliable
- Working offline

### Alternatives

-

### Additional context

_No response_

### How experienced are you with this library?

Expert - Experienced and comfortable with using this library in complex projects

### Are you interested in working on a PR for this?

- [ ] I want to work on this

### PR DESCRIPTION
**Pull request by exaby73**
Previously we downloaded all templates regardless of which command was run. This caused unecessary time to be wasted if all the user wanted to do is run `serverpod version` for example. This PR moves the template downloading logic to the `create` command specifically.

Fixes #3770

## Pre-launch Checklist

- [X] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [X] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [X] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [X] I added new tests to check the change I am making.
- [X] All existing and new tests are passing.
- [X] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

### CODE REVIEW

File: tools/serverpod_cli/lib/src/commands/create.dart [hunk 1]
```diff
@@ -89,6 +90,22 @@ class CreateCommand extends ServerpodCommand<CreateOption> {
...
+    // Make sure all necessary downloads are installed
+    if (!resourceManager.isTemplatesInstalled) {
+      try {
+        await resourceManager.installTemplates();
+      } catch (e) {
+        log.error('Failed to download templates.');
+        throw ExitException.error();
+      }
+
+      if (!resourceManager.isTemplatesInstalled) {
```
Comment (tp) [inline tools/serverpod_cli/lib/src/commands/create.dart:102]: Is this needed?

I think `installTemplate` already errors on each error, right?

The bigger problem (unrelated to this move) is that `isTemplatesInstalled` just checks the existence of the dir, not if the dir was ever written to successfully. 

Likewise `isTemplatesInstalled` does nothing if the dir exists already.

So I think in case the user is offline during the first run, this'll be broken "forever" (on that version).

Probably a better approach would be to use a temp download dir and then move that in the end (if that can be done atomically), or at least only create the dir when the file is received, so that the unzipping very likely succeeds.

**Review by tp — APPROVED** [review]
LGTM.

I think the moved code could be improved a bit.

(And then also the implementation.)

But for just fixing the original issue this'll do fine.

File: tools/serverpod_cli/lib/src/commands/create.dart (hunk 1 above)
Comment (exaby73) [reply tools/serverpod_cli/lib/src/commands/create.dart:102]: Do you think this could be a separate issue which I could work on in a different PR or shall I fix this issue in the PR itself?

Comment (tp) [reply tools/serverpod_cli/lib/src/commands/create.dart:102]: Your call.

Feel free to isolate the fix in a later PR. We just shouldn't lose track of this, because apart from the code clarity issue here (just mildly annoying), the fact that a developer might get stuck on "not downloaded" templates seems a much bigger issue from which there is no obvious way to recover.

PS: Hence the initial ✅, which means overall fine, and any comments are just for your consideration.

Comment (exaby73) [reply tools/serverpod_cli/lib/src/commands/create.dart:102]: Created https://github.com/serverpod/serverpod/issues/3790 to track this issue. I'll pick it up soon
