### PR TITLE
fix: Add missing optional transaction in database relational methods

### LINKED ISSUE #2442: Exception when using attachRow() inside a transaction
**Describe the bug**
When using attachRow() to create a relationship between two records, the function executes successfully outside of the context of a transaction but fails when executed as part a transaction. The error is not particularly helpful:

```
Insights listening on port 8081
Server default listening on port 8080
Webserver listening on port 8082
METHOD CALL: internal.addDataLimetrack duration: 19199ms numQueries: 0 authenticatedUser: 3
DatabaseException: Failed to update row, no rows updated
#0      DatabaseConnection.updateRow (package:serverpod/src/database/adapters/postgres/database_connection.dart:226:7)
<asynchronous suspension>
#1      AddressAttachRowRepository.country (package:limetrack_server/src/generated/address.dart:508:5)
<asynchronous suspension>
#2      InternalEndpoint.addDataLimetrack.<anonymous closure> (package:limetrack_server/src/endpoints/internal_endpoint.dart:802:7)
<asynchronous suspension>
#3      PgConnectionImplementation.runTx.<anonymous closure> (package:postgres/src/v3/connection.dart:480:24)
<asynchronous suspension>
#4      Pool.withResource (package:pool/pool.dart:127:14)
<asynchronous suspension>
#5      PoolImplementation.withConnection (package:postgres/src/pool/pool_impl.dart:153:16)
<asynchronous suspension>
#6      Database.transaction (package:serverpod/src/database/database.dart:291:12)
<asynchronous suspension>
#7      InternalEndpoint.addDataLimetrack (package:limetrack_server/src/endpoints/internal_endpoint.dart:800:5)
<asynchronous suspension>
#8      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:127:20)
<asynchronous suspension>
#9      Server._handleRequest (package:serverpod/src/server/server.dart:296:18)
<asynchronous suspension>
```

**To Reproduce**
1. Create a project with a simple one-to-many relationship
2. Insert the rows required to create the records
3. Use attachRow() to create the relationship between the records
4. Repeat steps 2 and 3 inside a transaction
5. See error

**Expected behavior**
I expected to be able to create the necessary relationships - using attachRow - within the context of a transaction. It's important to be able to use a transaction in order to rollback a series of inserts if anything goes wrong.

**Serverpod versions**
 -  _CLI Version:_ Serverpod version: 2.0.1
 - _Library version:_ 
  serverpod: 2.0.1
  serverpod_auth_server: 2.0.1
  serverpod_serialization: 2.0.1

**Platform information**
Server running in development mode on an Apple MacBook M1. Standard Docker deployment.

**Code snippet**
```dart
    // Lookups
    CompanyType? companyType = await CompanyType.db.findFirstRow(
      session,
      where: (t) => t.name.ilike('%private company%'),
    );

    Country? country = await Country.db.findFirstRow(
      session,
      where: (t) => t.name.ilike('%united kingdom%'),
    );

    // Data
    Address address = Address(line1: 'Address line 1', town: 'Town', postcode: 'PostCode');
    Carrier carrier = Carrier(companyName: 'Company Name');

    // Add data without transaction - WORKS
    Address newAddress = await Address.db.insertRow(session, address);
    await Address.db.attachRow.country(session, newAddress, country!);

    Carrier newCarrier = await Carrier.db.insertRow(session, carrier);
    await Carrier.db.attachRow.companyType(session, newCarrier, companyType!);
    await Carrier.db.attachRow.registeredAddress(session, newCarrier, newAddress);

    // Add data with transaction - FAILS
    await session.db.transaction((transaction) async {
      Address newTxnAddress = await Address.db.insertRow(session, address, transaction: transaction);
      // This call fails with the above exception
      await Address.db.attachRow.country(session, newTxnAddress, country!);

      Carrier newTxnCarrier = await Carrier.db.insertRow(session, carrier, transaction: transaction);
      await Carrier.db.attachRow.companyType(session, newTxnCarrier, companyType!);
      await Carrier.db.attachRow.registeredAddress(session, newCarrier, newTxnAddress);
    });

```

### PR DESCRIPTION
**Pull request by hampuslavin**
## Description
- The `transaction` parameter was not exposed in all database methods which means they could not be used in the context of a transaction (see #2442 for an example).
- There might be tests missing (please point out if you think so) but primarily the existing test had an incorrect expectation where transaction was missing from expected parameters.

## Changes
- Adds an optional `transaction` parameter to all database methods where it was missing, which fixes #2442

## Pre-launch Checklist
- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart [hunk 1]
```diff
@@ -131,16 +133,30 @@ void main() async {
...
+        });
         await UniqueData.db.insertRow(session, data3, transaction: transaction);
       },
     );
 
     var fetchedData = await UniqueData.db.find(session);
 
     expect(fetchedData, isNotEmpty);
-    expect(fetchedData, hasLength(2));
+    expect(fetchedData, hasLength(3));
```
Comment (hampuslavin) [inline tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart:157]: @SandPod I thought I'd extend this test to include the nested case, since it does prove an important aspect. It's not directly related to the fix in this PR, but maybe we can sneak it in here? Or would you like me to open a separate PR for it?

Comment (SandPod) [reply tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart:157]: Makes total sense to add a new test for this, but how about adding it as a separate scenario? Maybe we could have a discussion around how the nested transaction test could be structured to make it as simple as possible but still capture the essence of it.

File: tools/serverpod_cli/lib/src/generator/dart/library_generators/class_generators/repository_classes.dart [hunk 2]
```diff
@@ -915,8 +915,17 @@ class BuildRepositoryClass {
                 subDirParts: classDefinition.subDirParts,
                 config: config,
               );
-          })
+          }),
         ])
+        ..optionalParameters.add(
```
Comment (SandPod) [inline tools/serverpod_cli/lib/src/generator/dart/library_generators/class_generators/repository_classes.dart:920]: Comment when reviewing: Would have been great to include the unit tests for this change in this commit as well (I'm reviewing commit by commit).

File: tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart [hunk 3]
```diff
@@ -261,10 +261,11 @@ void main() {
         expect(peopleMethod, isNotNull, reason: 'Missing people method.');
       });
 
-      test('people method has the input params of session, person', () {
+      test('people method has the input params of session, person, transaction',
+          () {
         expect(
           peopleMethod?.parameters?.toSource(),
-          '(_i1.Session session, Person person)',
+          '(_i1.Session session, Person person, {_i1.Transaction? transaction})',
```
Comment (SandPod) [inline tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart:268]: Question: It feels like you patched it in more places than are covered in the tests here, are we missing scenarios in the test?

**Review by SandPod — COMMENTED** [review]
Nice work!

One suggestion to change around the added transaction test and then a question around if we cover all scenarios.

File: tools/serverpod_cli/lib/src/generator/dart/library_generators/class_generators/repository_classes.dart (hunk 2 above)
Comment (hampuslavin) [reply tools/serverpod_cli/lib/src/generator/dart/library_generators/class_generators/repository_classes.dart:920]: Can absolutely do that in the future 👍

File: tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart (hunk 3 above)
Comment (hampuslavin) [reply tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart]: Updated false-positive existing tests here: [9db6c80](https://github.com/serverpod/serverpod/pull/2656/commits/9db6c80c924d89da0e26e36c0b12aa819c3c4fd3)
Added additional integration tests here: 
617ddc3

File: tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart [hunk 4]
```diff
@@ -171,13 +171,12 @@ void main() {
...
-      test('people method has the input params of session, example and person',
+      test(
+          'people method has the input params of session, example, person and named param transaction',
           () {
         expect(
           peopleMethod?.parameters?.toSource(),
-          matches(
-            r'(_i\d.Session session, Example example, Person person)',
-          ),
+          r'(_i1.Session session, Example example, Person person, {_i1.Transaction? transaction})',
```
Comment (SandPod) [inline tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart:179]: Suggestion: Revert back to `\d` since the order of import does not matter.

Comment (SandPod) [reply tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart:179]: Same for the other tests.

File: tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart [hunk 5]
```diff
@@ -143,4 +143,53 @@ void main() async {
...
+        );
+      },
+    );
+
+    var fetchedData = await UniqueData.db.find(session);
+    expect(fetchedData, hasLength(1));
+    expect(fetchedData.elementAtOrNull(0)?.number, data.number);
+  });
+
+  test(
```
Comment (SandPod) [inline tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart:171]: Suggestion: Could we add a test that validate that "both" transactions are not canceled when calling cancel on the inner transaction?

**Review by SandPod — COMMENTED** [review]
Just one thought regarding the transaction test and a small nit for the test matching.

File: tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart (hunk 4 above)
Comment (hampuslavin) [reply tools/serverpod_cli/test/generator/dart/server_code_generator/database_repository_class_list_relation_additions_test.dart]: Brought back regex matching and fixed them: [282b62e](https://github.com/serverpod/serverpod/pull/2656/commits/282b62e86e6491db117e5028e0a985c6672f0429)

File: tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart (hunk 5 above)
Comment (hampuslavin) [reply tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart:171]: Added additional test: [bc2badf](https://github.com/serverpod/serverpod/pull/2656/commits/bc2badf01ab75e040b9c81693b49663b6fc9dcaf)

**Review by SandPod — APPROVED** [review]
