### PR TITLE
fix: Fixes #2826, HTTP code 500 instead of 400 upon param errors

### LINKED ISSUE #2826: Serverpod server responds with HTTP code 500 instead of 400 upon wrong endpoint parameters
## Version:

SERVERPOD version: 2.1.1, dart: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64", time: 2024-10-07 13:43:46.766788Z

## To reproduce:

Start a serverpod mini project, e.g. the example project with the endpoint `example`.

Invoke the endpoint method using curl with first correct parameters and then incorrect parameters. The second case should return the HTTP error code 400 (bad request) instead of 500 (internal server error).

```
$ curl -i "localhost:8080/example" -H "Content-Type: application/json" -d '{"method": "hello", "name": "Christer"}'
HTTP/1.1 200 OK
transfer-encoding: chunked
access-control-allow-origin: *
access-control-allow-methods: POST
x-frame-options: SAMEORIGIN
content-type: application/json; charset=utf-8
x-xss-protection: 1; mode=block
x-content-type-options: nosniff

"Hello Christer, the time is 2024-10-07 15:44:42.711563"

$ curl -i "localhost:8080/example" -H "Content-Type: application/json" -d '{"method": "hello"}'
HTTP/1.1 500 Internal Server Error
transfer-encoding: chunked
access-control-allow-origin: *
access-control-allow-methods: POST
x-frame-options: SAMEORIGIN
content-type: text/plain; charset=utf-8
x-xss-protection: 1; mode=block
x-content-type-options: nosniff

Internal server error. Call log id: 1051605082

```

## Server error log is:

```
Instance of 'InvalidParametersException'
#0      parseParameters (package:serverpod/src/server/endpoint_parameter_helper.dart:26:7)
#1      EndpointDispatch._getEndpointMethodConnector (package:serverpod/src/server/endpoint_dispatch.dart:157:27)
<asynchronous suspension>
#2      EndpointDispatch.getMethodCallContext (package:serverpod/src/server/endpoint_dispatch.dart:120:9)
<asynchronous suspension>
#3      Server._handleUriCall (package:serverpod/src/server/server.dart:466:31)
<asynchronous suspension>
#4      Server._handleRequest (package:serverpod/src/server/server.dart:293:18)
<asynchronous suspension>
#5      Server._handleRequestWithErrorBoundary (package:serverpod/src/server/server.dart:182:5)
<asynchronous suspension>

```

### PR DESCRIPTION
**Pull request by christerswahn**
Fixes the issue where Serverpod server responds with HTTP code 500 instead of 400 upon wrong endpoint parameters.

Closes #2826 

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes
Breaks previous error response behavior, but that behavior was wrong and upon discussion in team this was deemed ok.

### CODE REVIEW

File: packages/serverpod/lib/src/server/server.dart [hunk 1]
```diff
@@ -526,11 +527,8 @@ class Server {
       return ResultInvalidParams(e.message);
     } on NotAuthorizedException catch (e) {
       return e.authenticationFailedResult;
-    } on InvalidParametersException catch (e, stackTrace) {
```
Comment (christerswahn) [inline packages/serverpod/lib/src/server/server.dart:529]: This change could in theory be a breaking change. Is the sessionLogId used / needed in this error scenario? Note that this code seems to be rather old, >4 ys, if I parsed the history correctly.

File: packages/serverpod/lib/src/server/endpoint_dispatch.dart [hunk 2]
```diff
@@ -449,14 +449,20 @@ class ResultInvalidParams extends Result {
   }
 }
 
-/// The result of a failed [EndpointDispatch.getMethodStreamCallContext], [EndpointDispatch.getMethodCallContext] or [EndpointDispatch.getEndpointConnector] call.
-abstract class GetAuthorizedEndpointMethodException implements Exception {
+/// The result of a failed [EndpointDispatch.getMethodStreamCallContext],
+/// [EndpointDispatch.getMethodCallContext] or [EndpointDispatch.getEndpointConnector] call.
+abstract class GetEndpointMethodException implements Exception {
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/endpoint_dispatch.dart:454]: Is `EndpointDispatchException` a better name?

**Review by vlidholt — COMMENTED** [review]
LGTM, with suggested change. But someone else should have a look too. 🙂

File: packages/serverpod/lib/src/server/server.dart (hunk 1 above)
Comment (SandPod) [reply packages/serverpod/lib/src/server/server.dart:529]: TLDR; Change looks safe to me! 👍 

### Logging Id
Logically speaking I don't think logging the Session Id makes a lot of sense until the request has reached the endpoint. Before that the session hasn't really been "opened" even if the object is created.

The session id is also unique for each method call session created (the override is not used in this codepath): https://github.com/serverpod/serverpod/blob/a19e1660f236423349a65340a8b6a2fa9630a4a8/packages/serverpod/lib/src/server/session.dart#L145

So it won't help with debugging calls to the client.

In my opinion this is fine to remove.

### Logging in general
Logging changes level, we won't automatically print these to the server logs if a flag (configured through insights or server start) is not enabled. But I don't think this is a bad thing.

Now: https://github.com/serverpod/serverpod/blob/a19e1660f236423349a65340a8b6a2fa9630a4a8/packages/serverpod/lib/src/server/server.dart#L298-L302

Before: 
https://github.com/serverpod/serverpod/blob/a19e1660f236423349a65340a8b6a2fa9630a4a8/packages/serverpod/lib/src/server/server.dart#L320-L322

### Client representation
On the client side we will change the representation of these errors: https://github.com/serverpod/serverpod/blob/a19e1660f236423349a65340a8b6a2fa9630a4a8/packages/serverpod_client/lib/src/serverpod_client_shared_private.dart#L46-L53

But since this is an already known exception that had to be handled before I think this is completely fine.

Comment (SandPod) [reply packages/serverpod/lib/src/server/server.dart:529]: My only though is if we should return a 404 if the endpoint is not found? I'm not sure that makes a lot of sense since the endpoint dispatching depends on request body?

File: tests/serverpod_test_server/test_e2e/http_codes_test.dart [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+        Uri.parse('${serverUrl}simple'),
+        body: jsonEncode({
+          'method': 'hello',
+          'name': 'Starbase Alpha',
+          'extra': 'spurious value',
+        }),
+      );
+
+      expect(response.statusCode, 400);
+    }, skip: 'desired behavior unclear');
```
Comment (SandPod) [inline tests/serverpod_test_server/test_e2e/http_codes_test.dart:56]: Suggestion: The desired behavior here is to ignore any additional parameters. We have tests validating this behavior for the parameter parsing.

I think this is usually common practice when parsing query parameters, but it also enables us to be backwards compatible with old clients even if a parameter is removed from an endpoint.

File: tests/serverpod_test_server/test_e2e/http_codes_test.dart [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+
+    test(
+        'when calling an endpoint method with misspelled method name '
+        'then it should respond with 400 bad request', () async {
+      var response = await http.post(
+        Uri.parse('${serverUrl}simpleMistake'),
```
Comment (SandPod) [inline tests/serverpod_test_server/test_e2e/http_codes_test.dart:62]: Suggestion: To make this test more robust you could generate the method name with a UUID.

"misspelled" or "non-existing" does not really matter for this case. To make this test resistant towards someone actually introducing an endpoint called "simpleMistake" we could just as well generate a UUID for the method name and prove the same point.

**Review by SandPod — COMMENTED** [review]
Nice work!

Glad to get correct HTTP codes for invalid requests. This should reduce invaluable error logging on the server quite a bit.

Just had one though around the test for additional params. We might as well document the current desired behavior.

File: tests/serverpod_test_server/test_e2e/http_codes_test.dart (hunk 3 above)
Comment (christerswahn) [reply tests/serverpod_test_server/test_e2e/http_codes_test.dart:56]: Playing devil's advocate:
On the other hand, removing a parameter is a customer-space decision, and perhaps the framework shouldn't force that sort of backwards compatibility and thereby preventing what can be desired error handling.

Also, parameters are sent in the message body so it's not a case of HTTP query convention, rather it is a Serverpod protocol decision.

And finally, getting an intelligable error message when misspelling in Postman or on the Curl command line is superior UX! :)

Comment (christerswahn) [reply tests/serverpod_test_server/test_e2e/http_codes_test.dart:56]: BUT even if so, perhaps now is not the time to change this design which has been decided upon and there are tests for!

Comment (SandPod) [reply tests/serverpod_test_server/test_e2e/http_codes_test.dart:56]: Good points!

> ...parameters are sent in the message body so it's not a case of HTTP query convention rather it is a Serverpod protocol decision.

Very true, this is a design decision in the Serverpod protocol. We can deviate from normal query parsing conventions here if we have reason to do so.

> ...getting an intelligable error message when misspelling in Postman or on the Curl...

I'm not sure I follow how it would help in this case? 

Regardless, changing this would be a breaking change for existing clients so it is not actionable at this time.

File: packages/serverpod/lib/src/server/server.dart (hunk 1 above)
Comment (christerswahn) [reply packages/serverpod/lib/src/server/server.dart:529]: 404 when the path name (endpoint class name) is wrong would actually be more compliant with HTTP. Actual method name should be 400 as you say. I'll look into it!

File: packages/serverpod/lib/src/server/server.dart [hunk 5]
```diff
@@ -425,7 +436,8 @@ class Server {
     var path = uri.pathSegments.join('/');
     var endpointComponents = path.split('.');
     if (endpointComponents.isEmpty || endpointComponents.length > 2) {
-      return ResultInvalidParams('Endpoint $path is not a valid endpoint name');
+      return ResultNoSuchEndpoint(
```
Comment (SandPod) [inline packages/serverpod/lib/src/server/server.dart:439]: Suggestion: Revert this change.

As far as I understand, this is more of a formatting exception/invalid params exception rather than a no such endpoint exception right? And how does this tie together with the error validation done on line 472?

Comment (SandPod) [reply packages/serverpod/lib/src/server/server.dart:439]: Hampus made some effort consolidating our endpoint parsing logic so that it is a shared path regardless of how the protocol layer is implemented. So endpoint dispatch currently owns the knowledge about possible endpoints.

I think it is enough returning this exception based on that knowledge, as you have already implemented on line 538.

File: tests/serverpod_test_server/test_e2e/http_codes_test.dart [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+          'method': 'hello',
+        }),
+      );
+
+      expect(response.statusCode, 400);
+      expect(response.body, contains('Missing required query parameter: name'));
+    });
+
+    test(
+        'when calling an endpoint method with misspelled endpoint path '
```
Comment (SandPod) [inline tests/serverpod_test_server/test_e2e/http_codes_test.dart:45]: Suggestion(NIT): 
```suggestion
        'when calling an endpoint method with non-existing endpoint path '
```

File: tests/serverpod_test_server/test_e2e/http_codes_test.dart [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+          'name': 'Starbase Alpha',
+        }),
+      );
+
+      expect(response.statusCode, 404);
+      expect(response.body, contains('Endpoint $nonExistingPath not found'));
+    });
+
+    test(
+        'when calling an endpoint method with misspelled method name '
```
Comment (SandPod) [inline tests/serverpod_test_server/test_e2e/http_codes_test.dart:62]: Suggestion(NIT):
```suggestion
        'when calling an endpoint method with non-existing method name '
```

**Review by SandPod — COMMENTED** [review]
One question around the recent changes made. I think we can just revert that specific change and the PR is good to go with nice new 404s!
