### PR TITLE
fix: Export VerificationCodeConfig in serverpod_auth_idp_flutter

### LINKED ISSUE #4672: [bug] VerificationCodeConfig is not exported in serverpod_auth_idp_flutter
### Describe the bug

When customizing EmailSignInWidget (e.g., changing code length to 6), I need to configure the Flutter side to match. However, VerificationCodeConfig is not accessible without a deep import, which prevents the IDE from recognizing the class.

doc: https://docs.serverpod.dev/concepts/authentication/providers/email/customizing-the-ui

### To reproduce

Try to use VerificationCodeConfig in a fresh Serverpod 3.2.3 project.

Image

### Expected behavior

VerificationCodeConfig should be exported.

### Library version

  - serverpod_flutter: 3.2.3
  - serverpod_auth_idp_flutter: 3.2.3

### Platform information

MacOS (though this issue is platform-independent)

### Additional context

_No response_

### How experienced are you with this library?

Beginner - Just getting started with this library

### Are you interested in working on a PR for this?

- [x] I want to work on this

### PR DESCRIPTION
**Pull request by NeroSong**
VerificationCodeConfig is required to customize EmailSignInWidget (e.g., changing code length), but it's currently hidden in src/. This PR exports it to the public API.

Fix #4672

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

## Breaking changes

No

### CODE REVIEW

**Comment by NeroSong** [comment]
I have read the CLA Document and I hereby sign the CLA

File: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_flutter/lib/serverpod_auth_idp_flutter.dart [hunk 1]
```diff
@@ -21,6 +21,7 @@ export 'src/common/oauth2_pkce/oauth2_pkce_result.dart';
 export 'src/common/oauth2_pkce/oauth2_pkce_util.dart';
 export 'src/email/email_auth_controller.dart';
 export 'src/email/email_sign_in_widget.dart';
+export 'src/email/forms/verification.dart' show VerificationCodeConfig;
```
Comment (marcelomendoncasoares) [inline modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_flutter/lib/serverpod_auth_idp_flutter.dart]: Suggestion: Instead of exporting here, move the export to the `src/email/email_sign_in_widget.dart` file. This follows the patter on other files, such as `src/email/forms/verification.dart` to make all configs related to a widget available with no need for extra imports.

Comment (NeroSong) [reply modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_flutter/lib/serverpod_auth_idp_flutter.dart]: Done! I've moved the export to `src/email/email_sign_in_widget.dart` as suggested. Thanks for the review ☺️
