### PR TITLE
Fix: Support named and optional args in test tools

### LINKED ISSUE #2783: Named and optional arguments are not generated in the test tools endpoints
**Describe the bug**
Named and optional arguments are not generated in the test tools endpoints.

### PR DESCRIPTION
**Pull request by hampuslavin**
## Description
Adds support for named and optional args in test tools endpoint generation.

💡 It is starting to seem like some of the generation logic should be broken out so that it can be used by both the test tools generator and the client generator. For example, if we will add support for default args that logic will need to be added in 2 places. However, I think that should be a separate PR (perhaps even as part of the default value PR).

Closes #2783 

## Changes
- Adds code generation for two more types of parameters
  - optional positional
  - named
- Adds both snapshot tests in `test_tools_test.dart` as well as interface tests from user POV in `protocol_test.dart`.
  - 💡 Note that there is an overlap between `protocol_test.dart` and `return_and_input_types_test.dart`. I was about to merge them, but in the end I thought it was a bit nice to have them separate because they are testing slightly different aspects. The idea with `protocol_test.dart` is to just test all permutations of inputs, but not advanced behaviors like two users posting to a stream. Let me know if you think they should be merged!

## Pre-launch Checklist
- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

### CODE REVIEW

File: tests/serverpod_test_server/lib/src/endpoints/test_tools.dart [hunk 1]
```diff
@@ -108,3 +108,63 @@ class AuthenticatedTestToolsEndpoint extends Endpoint {
     }
   }
 }
+
+class TestToolsWithArgVariationsEndpoint extends Endpoint {
```
Comment (SandPod) [inline tests/serverpod_test_server/lib/src/endpoints/test_tools.dart:112]: Discussion: Would it make sense to add all these permutations once and then test them both form the "real" generated client in e2e tests and also the test framework?

This will help us validate we actually have client and test framework support for these?

File: tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+        () async {
+      final result =
+          await endpoints.testToolsWithArgVariations.echoOptionalArg(session);
+      expect(result, isNull);
+    });
+
+    test('when calling method with positional and named args then echoes args',
+        () async {
+      final result =
+          await endpoints.testToolsWithArgVariations.echoPositionalAndNamedArgs(
```
Comment (SandPod) [inline tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart:54]: Suggestion(NIT): Add test for when named arg is omitted.

To complete the matrix, this seems to have been missed.

File: tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+      );
+
+      expect(result, ['PositionalArg', 'NamedArg']);
+    });
+
+    test(
+        'when calling method with positional and optional args then echoes both args',
+        () async {
+      final result = await endpoints.testToolsWithArgVariations
+          .echoPositionalAndOptionalArgs(
```
Comment (SandPod) [inline tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart:67]: Suggestion(NIT): Add test for when optional arg is omitted.

To complete the matrix, this seems to have been missed.

File: tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart [hunk 4]
```diff
@@ -58,6 +58,12 @@ abstract base class MethodDefinition {
   /// The named parameters of this method.
   final List<ParameterDefinition> parametersNamed;
 
+  List<ParameterDefinition> get allParameters => [
```
Comment (SandPod) [inline tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart:61]: Comment: Nice 🌟

Comment (SandPod) [reply tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart:61]: Suggestion: Would be nice to use this where possible in the library generator as well.

To ensure this refactor doesn't diverge the code.

**Review by SandPod — COMMENTED** [review]
Nice work!

Couple of comments and suggestions.
Let me know what you think.

File: tests/serverpod_test_server/lib/src/endpoints/test_tools.dart (hunk 1 above)
Comment (hampuslavin) [reply tests/serverpod_test_server/lib/src/endpoints/test_tools.dart:112]: Sounds like a good idea, will investigate!

File: tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart (hunk 4 above)
Comment (hampuslavin) [reply tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart:61]: Good suggestion, will fix!

File: tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart (hunk 2 above)
Comment (hampuslavin) [reply tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart]: 45245d4

File: tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart (hunk 3 above)
Comment (hampuslavin) [reply tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart:92]: 45245d4

File: tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart (hunk 4 above)
Comment (hampuslavin) [reply tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart:61]: b15a517

File: tests/serverpod_test_server/lib/src/endpoints/test_tools.dart (hunk 1 above)
Comment (hampuslavin) [reply tests/serverpod_test_server/lib/src/endpoints/test_tools.dart]: Made an attempt here, let me know what you think of its placement/naming: 556ae12

File: tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart [hunk 5]
```diff
@@ -60,6 +60,31 @@ void main() {
       expect(result, ['PositionalArg', 'NamedArg']);
     });
 
+    test(
+        'when calling method with positional and nullable named args when passing value then echoes args',
```
Comment (SandPod) [inline tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart:64]: Suggestion: Change description to: `when calling method with positional and nullable named args with named arg then echoes args.`.

**Review by SandPod — APPROVED** [review]
LGTM! 🚀

File: tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart (hunk 5 above)
Comment (hampuslavin) [reply tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart]: 75fa6ce
