### PR TITLE
fix(auth): GoogleAuth.clientSecret not initialized when trying to authenticate from the client

### LINKED ISSUE #3722: Google client secret not loading in serverpod 2.9.0
### Describe the bug

I upgraded to serverpod 2.9.0 and doing so broke my sign-in-with-google flow.

the error I get is: "**The server side Google client secret is not loaded.**" from google_endpoint.dart, and it's seemingly because **nothing in the serverpod 2.9.0 codeflow appears to set the static GoogleAuth.clientSecret field**.

I can work around the issue by running this code at the end of my server.dart run method, which works because authClientForUser calls GoogleAuth._loadClientSecret.

Future<void> _googleAuthHack() async {
  await serverpod.withSession((session) async {
    try {
      logger.d("Runing _googleAuthHack");
      **await auth.GoogleAuth.authClientForUser(session, 1);**
    } catch (e, trace) {
      logger.e("googleAuthHack: $e", error: e, stackTrace: trace);
    }
  });
}

pls lmk if I'm missing anything or if this is an actual serverpod bug

btw 'withSession' is my own extension method for convenience:

extension ServerpodExtension on Serverpod {
  Future<T> withSession<T>(Future<T> Function(Session) func) async {
    final session = await createSession(enableLogging: true);
    try {
      return await func(session);
    } finally {
      await session.close(); // Clean up the session
    }
  }
}

### To reproduce

set up a project to use google authentication, including adding a google_client_secret.json to serverpod, then try to log in with google from the client-side. 

the client-side login nearly seems to complete, but then you get a 500 error. 

### Expected behavior

the google auth flow should complete normally. 

### Library version

2.9.0

### Platform information

testing end-to-end on localhost, on windows 11.

### Additional context

_No response_

### How experienced are you with this library?

None

### Are you interested in working on a PR for this?

- [ ] I want to work on this

### PR DESCRIPTION
**Pull request by exaby73**
Fix the issue when `GoogleEndpoint.authticate*` methods access `GoogleAuth.clientSecret` before `GoogleAuth.authClientForUser` was called which previously initialized `clientSecret`. Due to the previous behaviour, the case was that `clientSecret` would always be `null` preventing authenticating with Google. This should be fixed in this PR which adds back initialization of `clientSecret` immediately in an intializer.

Fixes #3722

## Pre-launch Checklist

- [X] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [X] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [X] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [X] I added new tests to check the change I am making.
- [X] All existing and new tests are passing.
- [X] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Summary by CodeRabbit

* **Refactor**
  * Improved the loading process for Google authentication client secrets, ensuring they are initialized once at startup for better performance and reliability. No changes to user-facing features or workflows.

### CODE REVIEW

File: modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart [hunk 1]
```diff
@@ -14,14 +14,15 @@ const _passwordKey = 'serverpod_auth_googleClientSecret';
 /// Convenience methods for handling authentication with Google and accessing
 /// Google's APIs.
 class GoogleAuth {
-  /// The client secret loaded from `config/google_client_secret.json`, null
-  /// if the client secrets failed to load.
-  static GoogleClientSecret? clientSecret;
+  /// The client secret loaded from `config/google_client_secret.json` or
+  /// password `serverpod_auth_googleClientSecret`, null if the client secrets
+  /// failed to load.
+  static final clientSecret = _loadClientSecret();
```
Comment (tp) [inline modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart:20]: So this was problematic for _another_ class wanting to access this and then getting `null`?

Comment (tp) [reply modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart:20]: Ah yes, see it in the endpoint now.

Looks good and makes sense :)

**Comment by tp** [comment]
@coderabbitai full review

File: modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart (hunk 1 above)
Comment (exaby73) [reply modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart:20]: Yes. My change to add password based config moved the intialization of this variable to `authClientForUser` which was an oversight

Comment (tp) [reply modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart:20]: (I also prefer that it can now be `final`, which makes it clear that this does not change later again (so others taking a reference to the instance is fine, as happens in the endpoint).)

**Comment by exaby73** [comment]
@tp to answer your question, we currently do not have any tests for `GoogleAuth` at the moment. This feature for password reading was added with the intention of providing a simple API for password based secrets, with the idea that this would be better handled in auth 2 with better test coverage and better code architecture.
