### PR TITLE
test: Fix verbose logging on tests that require the CLI

### LINKED ISSUE #3987: Excessive verbose logging during migration tests due to CLI dependency resolution
### Describe the bug

When running e2e migration tests in Docker containers (on the CI as well), the test output is flooded with verbose Dart pub dependency resolution logs (`FINE: Pub 3.8.0`, `SLVR: fact:`, `MSG : Resolving dependencies...`, etc.) for each test that creates a migration. This makes it extremely difficult to read test results and debug issues.

The verbose logs appear because the Serverpod CLI tool is performing dependency resolution for each `serverpod create-migration` command, despite the CLI being activated once at the beginning of the test run.

### To reproduce

1. Run the e2e migration tests:
   ```bash
   util/run_tests_migrations_e2e
   ```

2. Observe the output - each test that calls `MigrationTestUtils.createMigrationFromProtocols()` generates extensive pub dependency resolution logs like:
   ```
   tests-1 | +0: test_e2e_migrations/migrations_roundtrip_test.dart: Given new protocol model with table when creating and applying migration then database contains new table.
   tests-1 | FINE: Pub 3.8.0
   tests-1 | 
   tests-1 | MSG : Resolving dependencies...
   tests-1 | 
   tests-1 | SLVR: fact: serverpod_cli is 3.0.0-alpha.1
   tests-1 | SLVR: derived: serverpod_cli
   tests-1 | SLVR: fact: serverpod_cli depends on archive >=3.3.7 <5.0.0
   tests-1 | [... hundreds more lines of dependency resolution logs ...]
   ```

### Expected behavior

The CLI should cache its dependencies after the initial activation and not perform dependency resolution for each command invocation. Test output should be clean and focused on actual test results, with dependency resolution happening only once during CLI activation.

### Library version

- Serverpod: 3.0.0-alpha.1
- Dart: 3.8.0

### Platform information

- Docker container running `dart:3.8.0` base image
- Linux environment
- Container-based test execution

### Additional context

There is a simple (and somewhat hacky) solution that is quite simple: after activating the CLI in the `tests_e2e_migrations/run_tests.sh` file, call the serverpod CLI and activate the CLI again. Then, dependencies will be fully cached before any tests execute.

```bash
cd tools/serverpod_cli
dart pub global activate -s path . > /dev/null 2>&1

# Force the CLI to be activated and cache dependencies
serverpod version > /dev/null 2>&1
dart pub global activate -s path . > /dev/null 2>&1
```

### How experienced are you with this library?

Expert - Experienced and comfortable with using this library in complex projects

### Are you interested in working on a PR for this?

- [x] I want to work on this

### PR DESCRIPTION
**Pull request by marcelomendoncasoares**
Fixes #3987.

Also apply the same fix to other scripts and tests that activate the CLI.

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

N/A.

### CODE REVIEW

File: tests/docker/tests_e2e_migrations/run-tests.sh [hunk 1]
```diff
@@ -13,6 +13,11 @@ echo "### Serverpod home: $SERVERPOD_HOME"
 
 cd tools/serverpod_cli
 dart pub global activate -s path .
+
+# Force the CLI to be activated with cached dependencies
+serverpod version
+dart pub global activate -s path .
```
Comment (SandPod) [inline tests/docker/tests_e2e_migrations/run-tests.sh:19]: Question: I don't understand why a second activation would make a different? Do you have some reference documentation for this?

**Review by SandPod — APPROVED** [review]
I'll approve since it actually does reduce the number of lines written from 39k to 7k. But I'm not sure why a double activation would make a difference.

File: tests/docker/tests_e2e_migrations/run-tests.sh (hunk 1 above)
Comment (marcelomendoncasoares) [reply tests/docker/tests_e2e_migrations/run-tests.sh:19]: The closest issue I found was this https://github.com/dart-lang/pub/issues/4536, that running an activated package triggers upgrade. It is solved, but seems to be only on `dev` release and to be published on stable `3.10+`.

I don't understand 100% either, but this is aligned with what I do in my local environment (either, Windows, MacOS or Ubuntu on WSL) to avoid dependencies being downloaded for every command. And it is not only the double activation: if the executable is not called before the second activation, it has no effect. I tried multiple combinations, including only calling `pub get` instead, but this `activate` -> `call` -> `activate` was the only one that solved.
