### PR TITLE
fix(codegen): Fix `getClassNameForObject` for subclasses

### LINKED ISSUE #3730: PaginatedBookResult incorrectly serialized due to BasePaginatedResponse check order
### Describe the bug

Image

Image

<br/>

Image

<br/>
<br/>

### 📝 Issue Description

In the getClassNameForObject method within the Protocol class, the if (data is BasePaginatedResponse) condition is evaluated before the check for PaginatedBookResult. Since PaginatedBookResult extends BasePaginatedResponse, it always matches the base class condition first, leading to incorrect serialization.

### To reproduce

1. Suppose we have the following class structure:

   class Animal {}
   class Dog extends Animal {}

2. In the `getClassNameForObject` method, the checks are ordered like this:

   if (data is Animal) return "Animal";
   if (data is Dog) return "Dog";

3. Now create and pass an instance of Dog to the method.

4. Since Dog extends Animal, the first condition (`data is Animal`) evaluates to true and "Animal" is returned.

5. As a result, Dog is serialized with className: "Animal", causing incorrect deserialization later.

### Expected behavior

The method should prioritize subclass checks before superclass checks.

If an instance of `Dog` is passed, it should return "Dog" — not "Animal" — so that the full structure (including Dog-specific fields) can be correctly deserialized.

### Library version

2.9.0

### Platform information

Issue occurs in:
- Dart backend protocol class (serialization manager)
- Custom class serialization via `getClassNameForObject` method

### Additional context

_No response_

### How experienced are you with this library?

Beginner - Just getting started with this library

### Are you interested in working on a PR for this?

- [x] I want to work on this

### PR DESCRIPTION
**Pull request by tp**
Sorts classes in a hierarchy from child to parent, such that the `getClassNameForObject` gets the name of the most specific class, not a parent.

Closes #3730

### CODE REVIEW

File: tests/serverpod_test_client/lib/src/protocol/protocol.dart [hunk 1]
```diff
@@ -3701,28 +3701,28 @@ class Protocol extends _i1.SerializationManager {
     if (data is _i66.ExceptionWithData) {
       return 'ExceptionWithData';
     }
-    if (data is _i67.ChildClass) {
+    if (data.runtimeType == _i67.ChildClass) {
```
Comment (tp) [inline tests/serverpod_test_client/lib/src/protocol/protocol.dart]: Generating nested `if`s might read most clearly here.

File: tools/serverpod_cli/test/generator/dart/client_code_generator/protocol/inheritance_protocol_test.dart [hunk 2]
```diff
@@ -248,6 +248,21 @@ void main() {
             isTrue,
           );
         });
+
+        test(
```
Comment (tp) [inline tools/serverpod_cli/test/generator/dart/client_code_generator/protocol/inheritance_protocol_test.dart:252]: This test currently fails on `main`.

File: tests/serverpod_test_client/lib/src/protocol/protocol.dart [hunk 3]
```diff
@@ -345,224 +345,224 @@ class Protocol extends _i1.SerializationManager {
...
   ]) {
     t ??= T;
-    if (t == _i2.ByIndexEnumWithNameValue) {
-      return _i2.ByIndexEnumWithNameValue.fromJson(data) as T;
+    if (t == _i2.ScopeServerOnlyFieldChild) {
+      return _i2.ScopeServerOnlyFieldChild.fromJson(data) as T;
     }
-    if (t == _i3.ByNameEnumWithNameValue) {
-      return _i3.ByNameEnumWithNameValue.fromJson(data) as T;
+    if (t == _i3.ChildClass) {
```
Comment (tp) [inline tests/serverpod_test_client/lib/src/protocol/protocol.dart:351]: parent / child and sealed parent / sealed child are different hierarchies, so this is fine.

I also tried out the `switch` approach which did not have any more warnings with this sorting.

File: tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart [hunk 4]
```diff
@@ -1614,3 +1616,33 @@ extension on DatabaseDefinition {
...
   }
 }
+
+/// Sorts child classes before their parents, such that serialization order is stable.
+int _byChildClassesBeforeParents(
+  SerializableModelDefinition a,
+  SerializableModelDefinition b,
+) {
+  if (a is! ModelClassDefinition || b is! ModelClassDefinition) {
+    return 0;
```
Comment (nielsenko) [inline tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart:1626]: 🤔 .. seems odd

File: tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart [hunk 5]
```diff
@@ -1614,3 +1616,33 @@ extension on DatabaseDefinition {
...
+
+  if (a.extendsClass != null && b.extendsClass == null) {
+    return -1;
+  }
+
+  if (a.extendsClass == null && b.extendsClass != null) {
+    return 1;
+  }
+
+  if (a.extendsClass is ResolvedInheritanceDefinition &&
```
Comment (nielsenko) [inline tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart:1637]: could use new if `if (x case T)` syntax to avoid later cast

**Review by nielsenko — APPROVED** [review]
LGTM!

File: tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart (hunk 4 above)
Comment (tp) [reply tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart:1626]: I don't think we would even have such instances in practice here, just the way the list is typed…

Only this subclass has the inheritance, so everything else we can just leave as is.

File: tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart (hunk 5 above)
Comment (tp) [reply tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart:1637]: Right, that should be available now :)

File: tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart (hunk 4 above)
Comment (nielsenko) [reply tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart:1626]: Yes, I concluded that as well. Perhaps we could make capture that in the signature, or throw an exception here?

Anyway, not crucial.

Comment (Isakdl) [reply tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart:1626]: There is an enum definition class that is not a ModelClassDefinition if I'm not wrong? or did we refactor that?

**Review by Isakdl — CHANGES_REQUESTED** [review]
I suggest adding a test that runs the generated code and expects the model to resolve. E.g. replicate the bug in real running code not just by inspecting the generated code.

**Review by exaby73 — APPROVED** [review]
LGTM. Also agreed on @Isakdl's suggestion to add a test case for real code

File: tests/serverpod_test_server/test/class_name_for_object_test.dart [hunk 6]
```diff
@@ -74,6 +75,35 @@ void main() {
     expect(clientName, serverName);
   });
 
+  test(
```
Comment (tp) [inline tests/serverpod_test_server/test/class_name_for_object_test.dart:78]: @Isakdl Added this test case, which fails on `main` currently.

**Review by Isakdl — APPROVED** [review]
LGTM
