### PR TITLE
fix!: Fallback route cannot access session

### LINKED ISSUE #4344: Fallback route error with: `Bad state: ContextProperty value not found.`
### Describe the bug

When a fallback route is configured and it is triggered, it fails with the following error:

```bash
ERROR - 2025-12-01 22:38:02.369683
Method.get /hla/hla
Unhandled error in mounted handler.
Bad state: ContextProperty value not found. Property: Session. Ensure middleware has set this value for the request token.
package:relic/src/middleware/context_property.dart 52:10  ContextProperty.get
package:serverpod/src/web_server/web_server.dart 227:43   SessionEx.session
package:serverpod/src/web_server/web_server.dart 259:31   Route.call
package:relic/src/relic_server.dart 128:35                _RelicServer._handleRequest
```

### To reproduce

1. Create a new project from the template.
2. Modify the routes so that it looks like this:

```dart
  pod.webServer.addRoute(RootRoute(), '/');
  pod.webServer.addRoute(RootRoute(), '/index.html');
  pod.webServer.fallbackRoute = RootRoute();
```

3. Request a path that does not exist
4. Observe the issue.

### Expected behavior

Expects the fallback route to function without any issues.

### Library version

`3.0.0-rc.3`

### Platform information

MacOS.

### Additional context

_No response_

### How experienced are you with this library?

None

### Are you interested in working on a PR for this?

- [ ] I want to work on this

### PR DESCRIPTION
**Pull request by nielsenko**
- Defer session creation until actually needed using a `_Deferred` wrapper class
- Sessions are only created when `request.session` is awaited, avoiding unnecessary allocations
- Apply session and exception middleware to fallback route for consistent error handling
- Change `Request.session` return type from `Session` to `Future<Session>`

Fixes #4344

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else.
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

## Breaking changes

- `Request.session` now returns `Future<Session>` instead of `Session`
- `Request.sessionOrNull` now returns `Future<Session>?` instead of `Session?`

### CODE REVIEW

File: tests/serverpod_test_server/test/middleware_test.dart [hunk 1]
```diff
@@ -117,11 +117,12 @@ extension on Request {
 
 class _AuthMiddleware {
   Handler call(Handler next) {
-    return (ctx) async {
-      final info = await ctx.session.authenticated;
+    return (req) async {
+      final session = await req.session;
+      final info = await session.authenticated;
```
Comment (SandPod) [inline tests/serverpod_test_server/test/middleware_test.dart]: Question: This is not an await anymore, right?

File: packages/serverpod/lib/src/web_server/web_server.dart [hunk 2]
```diff
@@ -68,7 +68,12 @@ class WebServer {
   /// a request.
   ///
   /// If not set, default behavior is to return "404 Not Found".
-  set fallbackRoute(Route route) => _app.fallback = route.asHandler;
+  set fallbackRoute(Route route) =>
```
Comment (SandPod) [inline packages/serverpod/lib/src/web_server/web_server.dart:71]: Suggestion: Doesn't seem like we actually had any tests on fallback route. Could you add one?

File: tests/serverpod_test_server/test/middleware_test.dart (hunk 1 above)
Comment (nielsenko) [reply tests/serverpod_test_server/test/middleware_test.dart]: Since this is middleware (not a handler - `Route`), then we don't get the session as a parameter, but need to retrieve it from the request. Hence the `await req.session;`.

Comment (nielsenko) [reply tests/serverpod_test_server/test/middleware_test.dart]: But yes, `await session.authenticated;` is pointless. Funny that doesn't trigger a lint 🤔

**Comment by nielsenko** [comment]
Rebased on main

File: packages/serverpod/lib/src/web_server/web_server.dart (hunk 2 above)
Comment (nielsenko) [reply packages/serverpod/lib/src/web_server/web_server.dart:71]: Fixed in [e3e687a](https://github.com/serverpod/serverpod/pull/4347/commits/e3e687af93704e4c4de0671d2bbe11f071a3b9ad)

Note that I don't actually test that you can avoid session creation, by not touching `req.session`. I was a little lost at how to test this without accessing the private `_sessionPropterty` `ContextProperty` in _web_server.dart_

File: tests/serverpod_test_server/test/middleware_test.dart (hunk 1 above)
Comment (nielsenko) [reply tests/serverpod_test_server/test/middleware_test.dart]: Fixed

**Comment by nielsenko** [comment]
As futures start as soon as they are constructed in Dart, it is not enough to not await them. Hence `_Deferred` has been re-worked to take a `futureFactory` in [a229b97](https://github.com/serverpod/serverpod/pull/4347/commits/a229b97997897239b312621b8169f5e9282eb841)

**Comment by SandPod** [comment]
But it seems like they have broken some other functionality.

File: tests/serverpod_test_server/test/middleware_test.dart (hunk 1 above)
Comment (SandPod) [reply tests/serverpod_test_server/test/middleware_test.dart]: Leaving this comment open as a reminder that the CI should be green before we merge.

**Comment by nielsenko** [comment]
@SandPod I have re-worked `_Deferred` a bit. Now I track if future has been constructed, not if it ran to completion. See [30cd35c](https://github.com/serverpod/serverpod/pull/4347/commits/30cd35ccf31c0b446905887cce2c78ecee9f87fe).

**Review by SandPod — APPROVED** [review]
👍
