### PR TITLE
fix: Generator crashes when encountering field with `List, relation` missing the generic type argument

### LINKED ISSUE #2972: Concurrent modification during iteration: Instance(length:17) of '_GrowableList'.
**Describe the bug**

I tried to use chatgpt to generate serverpod model files for a new app. I teached serverpod with the 
https://github.com/serverpod/serverpod_docs/blob/main/docs/06-concepts/02-models.md

and my app idea. 

Chatgpt generated a bunch of .spy.yaml files which are looking good but makes serverpod generate crash with
Concurrent modification during iteration: Instance(length:17) of '_GrowableList'.

To simplify things it tried generate only the code for one this model files (I know that generated model files are not correct,
but it would be lovely to get an error message instead of an exception)

**To Reproduce**
1. serverpod create myapp

2. cd myapp;cd myapp_server

3. create inside lib/src/models/user.spy.yaml 
class: User
table: users
fields:
  id: int, isPrimaryKey, autoIncrement
  username: String, unique
  email: String, unique
  displayName: String
  calendarEvents: List<CalendarEvent>, relation
  createdAt: DateTime, default=now
  updatedAt: DateTime, default=now

4. serverpod generate
5. See error

Stack-Trace:
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling.
We would appreciate if you filed an issue over at Github. Please include the stack trace below and
describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues

```
Concurrent modification during iteration: Instance(length:17) of '_GrowableList'.

#0      ListIterator.moveNext (dart:_internal/iterable.dart:348:7)
#1      ModelDependencyResolver.resolveModelDependencies.<anonymous closure>
(package:serverpod_cli/src/analyzer/models/entity_dependency_resolver.dart:17:51)
#2      Iterable.forEach (dart:core/iterable.dart:347:35)
#3      ModelDependencyResolver.resolveModelDependencies
(package:serverpod_cli/src/analyzer/models/entity_dependency_resolver.dart:15:51)
#4      SerializableModelAnalyzer.resolveModelDependencies
(package:serverpod_cli/src/analyzer/models/model_analyzer.dart:95:36)
#5      StatefulAnalyzer._updateAllModels
(package:serverpod_cli/src/analyzer/models/stateful_analyzer.dart:113:31)
#6      StatefulAnalyzer.validateAll
(package:serverpod_cli/src/analyzer/models/stateful_analyzer.dart:71:5)
#7      performGenerate (package:serverpod_cli/src/generator/generator.dart:29:25)
<asynchronous suspension>
#8      StdOutLogger.progress (package:cli_tools/src/logger/loggers/std_out_logger.dart:141:20)
<asynchronous suspension>
#9      GenerateCommand.run (package:serverpod_cli/src/commands/generate.dart:69:17)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     BetterCommandRunner.runCommand
(package:cli_tools/src/better_command_runner/better_command_runner.dart:140:7)
<asynchronous suspension>
#12     ServerpodCommandRunner.runCommand
(package:serverpod_cli/src/runner/serverpod_command_runner.dart:103:5)
```

**Expected behavior**
Instead of an exception I except to get an error message.

I figured out, the main reason for this exception is this:
calendarEvents: List<CalendarEvent>, relation

Deleting "List" from the line and I get an error message instead of the exception.

**Serverpod versions**
 -  _CLI Version:  2.1.5
 - _Library version: 2.1.5

**Platform information**
Apple MacBookPro M1

Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (4 weeks ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

**Additional context**
Hope this helps, that took a while for figuring this out and open an issue.
This happens also on the latest 2.2.0 beta

Ok, I also learned that I have to feed the AI with https://github.com/serverpod/serverpod_docs/tree/main/docs/06-concepts/06-database/03-relations

### PR DESCRIPTION
**Pull request by tp**
Closes #2972

At first I thought to implement it on a lower level, e.g. not even allowing to generate an invalid `TypeDefinition` (e.g. when it's a `List` but does not have any (1!) generics specified). But that just leads to a low-level crash like the one in the linked issue.

So instead we have to stop the processing early in the error case, and then rely on the analyzer to spot that condition (as well) and prevent the code generation.

### CODE REVIEW

File: tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart [hunk 1]
```diff
@@ -1,11 +1,10 @@
 import 'dart:math';
 
-import 'package:super_string/super_string.dart';
-
 import 'package:serverpod_cli/src/analyzer/models/checker/analyze_checker.dart';
 import 'package:serverpod_cli/src/analyzer/models/definitions.dart';
 import 'package:serverpod_cli/src/generator/types.dart';
 import 'package:serverpod_shared/serverpod_shared.dart';
+import 'package:super_string/super_string.dart';
```
Comment (tp) [inline tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart:7]: I hope this was not by some convention, as my current VS Code sorted the imports this way.

File: tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/relation/relation_keyword_test.dart [hunk 2]
```diff
@@ -637,6 +637,37 @@ fields:
...
+      expect(definitions, isEmpty);
+    });
+
+    test('An error for the missing type is emitted.', () {
+      expect(
+        collector.errors.map((e) => e.message),
+        contains(matches('List type must have one generic type defined')),
+      );
+    });
+  });
```
Comment (Isakdl) [inline tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/relation/relation_keyword_test.dart:669]: Suggestion: As mentioned in the other PR, construct the full test description in the `given`, `when`, `then` format.

**Review by Isakdl — CHANGES_REQUESTED** [review]
Looking good, just a smaller request on the test descriptions.
