### PR TITLE
fix: CORS issue when making requests from swagger

### LINKED ISSUE #1434: Unable to Make Cross-Origin Requests to Endpoints from Different Locations
**Describe the bug**
I'm testing Swagger UI for endpoints, but I can't make requests, and it's failing at the OPTIONS preflight request, throwing a CORS error.

**To Reproduce**
1. create a ServerPod project and run
2. paste this json in [swagger editor ](https://editor.swagger.io/)
``` {
    "openapi": "3.0.0",
    "info": {
        "title": "ServerPod Endpoint - OpenAPI",
        "version": "0.0.1"
    },
    "servers": [
        {
            "url": "http://localhost:8080",
            "description": "Development Server"
        }
    ],
    "tags": [
        {
            "name": "example"
        }
    ],
    "paths": {
        "/example/hello": {
            "post": {
                "operationId": "helloExample",
                "tags": [
                    "example"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
            
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request (the query passed to the server was incorrect)."
                    },
                    "403": {
                        "description": "Forbidden (the caller is trying to call a restricted endpoint, but doesn't have the correct credentials/scope)."
                    },
                    "500": {
                        "description": "Internal server error "
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Example": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "data": {
                        "type": "integer"
                    }
                }
            }
        },
        "securitySchemes": {
            "serverpodAuth": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    }
}
```
3. Try to execute the example/hello endpoint

**Expected behavior**
It should return the following JSON response: {"hello": "sometext"}.

### PR DESCRIPTION
**Pull request by b14cknc0d3**
This pull request added `headers` in  `ServerPod` . Previously, we allowed all CORS requests with a wildcard (*). I added the capability to define specific CORS headers in the ServerPod configuration. Now, we can precisely control which hosts are allowed to make cross-origin requests by configuring headers.

resolve #1434

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

### CODE REVIEW

File: packages/serverpod/lib/src/server/server.dart [hunk 1]
```diff
@@ -65,6 +65,9 @@ class Server {
   /// Central message dispatch for real time messages.
   MessageCentral messageCentral = MessageCentral();
 
+  /// Define CORS headers to allow cross-origin requests.
+  final Map<String, dynamic> headers;
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/server.dart:69]: This defines any type of headers, just not for CORS, so the documentation should reflect this. Perhaps a more descriptive name would be good too. `httpResponseHeaders`?

`/// Http headers used by all API responses. Defaults to allowing any cross origin resource sharing (CORS).`

File: packages/serverpod/lib/src/server/server.dart [hunk 2]
```diff
@@ -205,6 +211,16 @@ class Server {
       readBody = false;
     }
 
+    /// This [OPTIONS] check is necessary when making requests from
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/server.dart:214]: Names in `[]` refers to other Dart code, so in this case should not be used. Also, the tripple dash comments are only used for Dart docs (here `//` double dashes should be used).

File: packages/serverpod/lib/src/server/serverpod.dart [hunk 3]
```diff
@@ -212,13 +212,26 @@ class Serverpod {
...
   Serverpod(
     List<String> args,
     this.serializationManager,
     this.endpoints, {
     this.authenticationHandler,
     this.healthCheckHandler,
+    this.headers = const {
+      'Access-Control-Allow-Origin':
+          '*', // Allow all origins or specify a specific origin.
+      'Access-Control-Allow-Methods':
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/serverpod.dart:228]: We are only using `POST` in Serverpod, so maybe this should be the only option allowed?

File: packages/serverpod/lib/src/server/serverpod.dart [hunk 4]
```diff
@@ -212,13 +212,26 @@ class Serverpod {
...
+          'GET, POST, PUT, DELETE', // Add allowed methods.
+      'Access-Control-Allow-Headers':
+          'Content-Type', // Add allowed headers if needed.
+      'Access-Control-Max-Age':
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/serverpod.dart:232]: Doesn't this risk requests being cached by browsers? Which would be bad as only static content should be cached.

File: packages/serverpod/lib/src/server/serverpod.dart [hunk 5]
```diff
@@ -212,13 +212,26 @@ class Serverpod {
...
     this.serializationManager,
     this.endpoints, {
     this.authenticationHandler,
     this.healthCheckHandler,
+    this.headers = const {
+      'Access-Control-Allow-Origin':
+          '*', // Allow all origins or specify a specific origin.
+      'Access-Control-Allow-Methods':
+          'GET, POST, PUT, DELETE', // Add allowed methods.
+      'Access-Control-Allow-Headers':
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/serverpod.dart:230]: Does this risk other headers being blocked by firewalls? E.g., forwarding of IP addresses through X-* headers, etc.

**Review by vlidholt — CHANGES_REQUESTED** [review]
Great addition! :) But we need to ensure that this works in all cases (see comments). Also, we should add a (end-to-end?) test for this.

File: packages/serverpod/lib/src/server/serverpod.dart (hunk 5 above)
Comment (b14cknc0d3) [reply packages/serverpod/lib/src/server/serverpod.dart:230]: I think  no impact on custom headers

Comment (vlidholt) [reply packages/serverpod/lib/src/server/serverpod.dart:230]: Think or know? I bad decision will impact 100s of users. 😅

**Comment by vlidholt** [comment]
We will also need a test for this, otherwise looks good as long as we can get some double check/test on the unresolved conversation. :)

File: packages/serverpod/lib/src/server/serverpod.dart (hunk 5 above)
Comment (b14cknc0d3) [reply packages/serverpod/lib/src/server/serverpod.dart:230]: I performed a test with a custom 'X-*'  header  , and it was not allowed. Our server configuration only permits the 'Content-Type' header.
Screenshot 2023-10-09 at 9 08 20 PM

File: packages/serverpod/lib/src/server/server.dart [hunk 6]
```diff
@@ -205,6 +214,20 @@ class Server {
...
 
+    // This OPTIONS check is necessary when making requests from
+    // eg `editor.swagger.io`. It ensures proper handling of preflight requests
+    // with the OPTIONS method.
+    if (request.method == 'OPTIONS') {
+      request.response.headers.add('Access-Control-Allow-Headers',
+          httpResponseHeaders['Access-Control-Allow-Headers']);
+
+      // Safari and other potential browsers required to set content-length=0
+      request.response.headers.add('Content-length', 0);
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/server.dart:225]: `Content-Length` (captial `L`)

File: packages/serverpod/lib/src/server/serverpod.dart [hunk 7]
```diff
@@ -212,13 +212,24 @@ class Serverpod {
...
+  final Map<String, dynamic> httpResponseHeaders;
+
   /// Creates a new Serverpod.
   Serverpod(
     List<String> args,
     this.serializationManager,
     this.endpoints, {
     this.authenticationHandler,
     this.healthCheckHandler,
+    this.httpResponseHeaders = const {
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/serverpod.dart:226]: Break this out into a local constant `_defaultHttpResponseHeaders`.

File: packages/serverpod/lib/src/server/server.dart [hunk 8]
```diff
@@ -152,8 +157,12 @@ class Server {
     serverpod
         .logVerbose('handleRequest: ${request.method} ${request.uri.path}');
 
-    // Set Access-Control-Allow-Origin, required for Flutter web.
-    request.response.headers.add('Access-Control-Allow-Origin', '*');
+    for (var header in httpResponseHeaders.entries) {
+      // The 'Access-Control-Allow-Headers' header should be included in the
+      // response only for OPTIONS requests.
+      if (header.key == 'Access-Control-Allow-Headers') continue;
+      request.response.headers.add(header.key, header.value);
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/server.dart:164]: This feels like a bit of black magic, and it's not clear that not all headers you pass in will be set. A better solution is to add a second parameter.

`httpOptionsResponseHeader` which can be configured just like `httpResponseHeader`.

**Review by vlidholt — CHANGES_REQUESTED** [review]
Great work, will be approved with the small changes outlined in the comments. :)

File: packages/serverpod/lib/src/server/server.dart (hunk 6 above)
Comment (b14cknc0d3) [reply packages/serverpod/lib/src/server/server.dart]: done

File: packages/serverpod/lib/src/server/serverpod.dart [hunk 9]
```diff
@@ -212,13 +212,32 @@ class Serverpod {
...
 
+  /// Http headers used by all API responses. Defaults to allowing any
+  /// cross origin resource sharing (CORS).
+  final Map<String, dynamic> httpResponseHeaders;
+
+  /// Http headers used by OPTIONS responses.
+  final Map<String, dynamic> httpOptionsResponseHeaders;
+
+  static const _defaultHttpResponseHeaders = {
+    'Access-Control-Allow-Origin': 'http://localhost:8082',
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/serverpod.dart:223]: This will clearly break things when not running on localhost (e.g. deploying to the cloud). It needs to be set to `'*'`.

File: packages/serverpod/lib/src/server/server.dart [hunk 10]
```diff
@@ -65,6 +65,13 @@ class Server {
   /// Central message dispatch for real time messages.
   MessageCentral messageCentral = MessageCentral();
 
+  /// Http headers used by all API responses. Defaults to allowing any
+  /// cross origin resource sharing (CORS).
+  final Map<String, dynamic> httpResponseHeaders;
+
+  /// Http headers used by OPTIONS responses.
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/server.dart:72]: Documentation should either make clear that these are in addition to the `httpResponseHeaders` or (better) by default include all headers.

File: packages/serverpod/lib/src/server/server.dart [hunk 11]
```diff
@@ -205,6 +215,21 @@ class Server {
...
 
+    // This OPTIONS check is necessary when making requests from
+    // eg `editor.swagger.io`. It ensures proper handling of preflight requests
+    // with the OPTIONS method.
+    if (request.method == 'OPTIONS') {
+      for (var header in httpOptionsResponseHeaders.entries) {
+        request.response.headers.add(header.key, header.value);
+      }
+
+      // Safari and other potential browsers required to set content-length=0
```
Comment (vlidholt) [inline packages/serverpod/lib/src/server/server.dart:226]: Spelling misstake here:
`// Safari and potentially other browsers require Content-Length=0.`

**Review by vlidholt — CHANGES_REQUESTED** [review]
Just some final touches. 😅

**Review by vlidholt — APPROVED** [review]
Great work! :D
