### PR TITLE
fix: Verify Google ID Token correctly

### LINKED ISSUE #2354: Google auth does nor work on iOS
**Describe the bug**
All instructions have been followed and authentication does not happen.

flutter: serverpod_auth_google: GoogleSignIn
flutter: serverpod_auth_google: serverAuthCode is null. Trying auth.idToken.
flutter: serverpod_auth_google: Signing out from google
flutter: serverpod_auth_google: Failed to authenticate with Serverpod backend: 0. Aborting.

**Expected behavior**
session maganager callback on auentication

**Serverpod versions**
 -  _CLI Version:_ 1.2.7
 - _Library version:_ 1.2.7

### LINKED ISSUE #2536: Failed to verify Google ID Token on server side
**Describe the bug**
While trying to work around sign in with Google on Windows using [google_sign_in_dartio](https://pub.dev/packages/google_sign_in_dartio), I managed to sign in thru the windows frontend but failed on back end, probably related to #2354.

**To Reproduce**
1. Follow the [Google auth](https://docs.serverpod.dev/concepts/authentication/providers/google) setup
2. Register the [google_sign_in_dartio](https://pub.dev/packages/google_sign_in_dartio)
3. Run the backend and windows frontend
4. Sign in with Google

**Expected behavior**
User info page displayed

**Screenshots**
Errors in debug console:
```
flutter: serverpod_auth_google: GoogleSignIn
flutter: result: {"state": ..........}
flutter: serverpod_auth_google: serverAuthCode is null. Trying auth.idToken.
flutter: serverpod_auth_google: Signing out from google
flutter: serverpod_auth_google: Failed to authenticate with Serverpod backend: invalidCredentials. Aborting.
```

**Serverpod versions**
 -  _CLI Version:_ 2.0.2
 - _Library version:_ 2.0.2

**Platform information**
Windows 11

### PR DESCRIPTION
**Pull request by htlam**
While trying to work around sign in with Google on Windows using [google_sign_in_dartio](https://pub.dev/packages/google_sign_in_dartio), I managed to sign in thru the windows frontend but failed on back end. After some digging into the auth module, I found that it was caused by the `authenticateWithIdToken` function in `google_endpoint.dart` failing to verify a valid ID token with `iss` equals `https://accounts.google.com`.

According to [Verify the Google ID token on your server side](https://developers.google.com/identity/gsi/web/guides/verify-google-id-token):

> The value of `iss` in the ID token is equal to `accounts.google.com` or `https://accounts.google.com`.

This PR fixed #2536 auth issues related to ID token flow.

It may also fixed #2354, but I do not have a Mac device to verify it.

## Pre-launch Checklist

- [X] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [X] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [X] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [X] All existing and new tests are passing.
- [X] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

None

### CODE REVIEW

**Comment by htlam** [comment]
I have read the CLA Document and I hereby sign the CLA

File: modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart [hunk 1]
```diff
@@ -149,7 +149,8 @@ class GoogleEndpoint extends Endpoint {
       }
 
       var data = jsonDecode(response.body);
-      if (data['iss'] != 'accounts.google.com') {
+      if (data['iss'] != 'accounts.google.com' &&
+          data['iss'] != 'https://accounts.google.com') {
```
Comment (Isakdl) [inline modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart:153]: Suggestion: Change this to an OR

This will fail every login attempt as both strings cannot be valid simultaneously.

**Review by Isakdl — CHANGES_REQUESTED** [review]
Thank you for the PR! :) 

You have to modify the if statement to an OR but otherwise looking good.

For future reference, the modification in this PR is correct according to the official google auth docs here: https://developers.google.com/identity/sign-in/web/backend-auth

File: modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart (hunk 1 above)
Comment (htlam) [reply modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart:153]: Thanks for the suggestion.
It should work because we use `!=` in the string comparison for the "failing both" logic.
But I agree to change it to an OR for the "not matching any" logic to clearly match the documentation.

**Review by Isakdl — APPROVED** [review]
LGTM
