### PR TITLE
fix: conditional sdk imports

### LINKED ISSUE #2377: v2.0 fails to compile serverpod_client in non-flutter environment.
**Describe the bug**
When trying to use the generated serverpod client in a non-flutter environment (i.e. Jaspr) this compilation error is thrown:

```
[BUILDER] [ERROR] Invalid argument(s): Unsupported conditional import of `dart:html` found in serverpod_client|lib/src/serverpod_client_shared_private.dart:
[BUILDER] [ERROR] 
[BUILDER] [ERROR] import 'dart:html' if (dart.library.io) 'dart:io';
[BUILDER] [ERROR] 
[BUILDER] [ERROR] This environment does not support direct conditional imports of `dart:` libraries. Instead you must create a separate library which unconditionally imports (or exports) the `dart:` library that you want to use, and conditionally import (or export) that library.
[BUILDER] [ERROR] Invalid argument(s): Unsupported conditional import of `dart:html` found in serverpod_client|lib/src/serverpod_client_exception.dart:
[BUILDER] [ERROR] 
[BUILDER] [ERROR] import 'dart:html' if (dart.library.io) 'dart:io';
[BUILDER] [ERROR] 
[BUILDER] [ERROR] This environment does not support direct conditional imports of `dart:` libraries. Instead you must create a separate library which unconditionally imports (or exports) the `dart:` library that you want to use, and conditionally import (or export) that library.
```

**To Reproduce**
Run the project at https://github.com/schultek/jaspr/tree/feat/serverpod/apps/dart_quotes_server

**Expected behavior**
Compiles without problems (as pre-2.0 did)

**Serverpod versions**
 -  _CLI Version:_ 2.0.1
 - _Library version:_ 2.0.1
 
**Additional context**

See related issues:
https://github.com/dart-lang/build/issues/3173
https://github.com/dint-dev/universal_html/pull/62

### PR DESCRIPTION
**Pull request by schultek**
Fixes #2377 

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

### CODE REVIEW

File: packages/serverpod_client/lib/src/serverpod_client_exception.dart [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import 'dart:html' if (dart.library.io) 'dart:io';
+import './_sdk/html.dart' if (dart.library.io) './_sdk/io.dart';
```
Comment (Isakdl) [inline packages/serverpod_client/lib/src/serverpod_client_exception.dart:1]: Suggestion: We are only interested in the class `HttpStatus` from these packages. It would be nice only to expose this class to these imports. 

I.E. 

```dart
export 'dart:io' show HttpStatus;
```

```dart
export 'dart:html' show HttpStatus;
```

And rename the files to reflect that we are only taking the `HttpStatus` class.

**Review by Isakdl — CHANGES_REQUESTED** [review]
Thank you for both the issue and the PR! 🚀 

I have a small requested change to better reflect the intent of these imports. It also follows the limitation dart have on conditional imports which should expose the exact same interface.

**Comment by schultek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Isakdl — CHANGES_REQUESTED** [review]
Last nit comment, please rename the folder `_sdk` to `http`

**Review by Isakdl — APPROVED** [review]
LGTM
