### PR TITLE
fix(test): Clear caches in between test runs

### LINKED ISSUE #3567: Local cache not reset between tests using `withServerpod`
## Describe the bug  
The local cache is not cleared between tests executed within the same `withServerpod` test group. This leads to state leakage across tests, which violates test isolation and causes false positives/negatives.

## To reproduce  
1. Create a new Serverpod project using the `serverpod create` template.  
2. Replace `greeting_endpoint.dart` with:

```dart
import 'generated/protocol.dart';
import 'package:serverpod/serverpod.dart';

class GreetingEndpoint extends Endpoint {
  Future<Greeting> hello(Session session, String name) async {
    await session.caches.local.put(
      'key',
      Greeting(message: 'test', author: 'author', timestamp: DateTime.now()),
      lifetime: const Duration(days: 1),
    );
    return Greeting(
      message: 'Hello $name',
      author: 'Serverpod',
      timestamp: DateTime.now(),
    );
  }
}
```

3. Replace `greeting_endpoint_test.dart` with:

```dart
import 'package:cache_bug_server/src/generated/greeting.dart';
import 'package:test/test.dart';
import 'test_tools/serverpod_test_tools.dart';

void main() {
  withServerpod('Given Greeting endpoint', (sessionBuilder, endpoints) {
    test('when calling `hello` with name then returned greeting includes name',
        () async {
      final greeting = await endpoints.greeting.hello(sessionBuilder, 'Bob');
      expect(greeting.message, 'Hello Bob');

      final session = sessionBuilder.build();
      final cached = session.caches.local.get<Greeting>('key');
      expect(cached, isNotNull);
    });

    test('cache should be empty', () async {
      final session = sessionBuilder.build();
      final cached = session.caches.local.get<Greeting>('key');
      expect(cached, isNull);
    });
  });
}
```

4. Run the tests.

## Expected behavior  
The second test should pass. Since the local cache should be reset between tests, `session.caches.local.get<Greeting>('key')` should return `null`.

## Library version  
- Serverpod version: latest main  
- Dart SDK: stable channel

## Platform information  
- Dart CLI (test runner)

## Additional context  
The current behavior causes shared state between tests, which makes test outcomes interdependent and unreliable. This issue likely stems from how `withServerpod` initializes sessions or how the local cache is scoped.

### PR DESCRIPTION
**Pull request by exaby73**
This PR aims to fix an issue where caches are not cleared in between different tests.

Fixes #3567

## Pre-launch Checklist

- [X] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [X] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [X] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [X] I added new tests to check the change I am making.
- [X] All existing and new tests are passing.
- [X] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Summary by CodeRabbit

* **New Features**
  * Added new methods for testing cache operations, including storing and retrieving data from various cache types.
  * Introduced integration tests to verify cache isolation and automatic cache cleanup between tests.
* **Tests**
  * Implemented comprehensive test suites to ensure proper cache behavior and isolation across different cache types and scenarios.

### CODE REVIEW

**Comment by exaby73** [comment]
@coderabbitai full review

File: packages/serverpod_test/lib/src/with_serverpod.dart [hunk 1]
```diff
@@ -157,6 +157,10 @@ void Function(TestClosure<T>)
             await localTransactionManager.addSavepoint();
           }
 
+          await mainServerpodSession.caches.local.clear();
+          await mainServerpodSession.caches.localPrio.clear();
+          await mainServerpodSession.caches.query.clear();
```
Comment (nielsenko) [inline packages/serverpod_test/lib/src/with_serverpod.dart]: Should we perhaps expose a cleanup method on `Caches`? Not critical for this PR, but either include it here or create an issue for it for later?

**Review by nielsenko — APPROVED** [review]
LGTM. Testing the test tools is always a bit convoluted.

File: packages/serverpod_test/lib/src/with_serverpod.dart (hunk 1 above)
Comment (exaby73) [reply packages/serverpod_test/lib/src/with_serverpod.dart]: Good idea! I'll add it to this PR :)

File: tests/serverpod_test_server/test_integration/test_tools/cache_isolation_test.dart [hunk 2]
```diff
@@ -0,0 +1,157 @@
+import 'package:serverpod_test_server/src/generated/protocol.dart';
+import 'package:test/test.dart';
+
+import 'serverpod_test_tools.dart';
+
+void main() {
+  withServerpod(
+    'Given withServerpod with cache operations',
+    (sessionBuilder, endpoints) {
+      group('when tests store data in local cache', () {
```
Comment (tp) [inline tests/serverpod_test_server/test_integration/test_tools/cache_isolation_test.dart:10]: I suppose we could just drop this, and then update the test descriptions accordingly:

File: tests/serverpod_test_server/test_integration/test_tools/cache_isolation_test.dart [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+        test('then local cache should be empty in subsequent tests', () async {
```
Comment (tp) [inline tests/serverpod_test_server/test_integration/test_tools/cache_isolation_test.dart]:
```suggestion
        test('when writing and reading from a cache in the same test, then the value is retrieved.', () async {
```

File: tests/serverpod_test_server/test_integration/test_tools/cache_isolation_test.dart [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+              .putInLocalCache(sessionBuilder, 'test-key', testData);
+
+          // Verify data was stored
+          final cached1 = await endpoints.testTools
+              .getFromLocalCache(sessionBuilder, 'test-key');
+          expect(cached1, isNotNull);
+          expect(cached1!.num, equals(42));
+        });
+
+        test('then local cache should be empty from previous test', () async {
```
Comment (tp) [inline tests/serverpod_test_server/test_integration/test_tools/cache_isolation_test.dart:24]:
```suggestion
        test('when accessing a cache key written in a previous `test`, then the value is `null`.', () async {
```

File: tests/serverpod_test_server/test_integration/test_tools/cache_isolation_test.dart [hunk 5]
```diff
@@ -0,0 +1,157 @@
+import 'package:serverpod_test_server/src/generated/protocol.dart';
+import 'package:test/test.dart';
+
+import 'serverpod_test_tools.dart';
+
+void main() {
+  withServerpod(
+    'Given withServerpod with cache operations',
+    (sessionBuilder, endpoints) {
```
Comment (tp) [inline tests/serverpod_test_server/test_integration/test_tools/cache_isolation_test.dart:9]: Should we add an extra test which checks that caches filled in `setUp` are _not_ cleared and visible inside the `test`?

**Review by tp — APPROVED** [review]
Great, aso for adding that extra test case :)
